# Set ENV_IP to run this compose. dev=2, main=1

version: '3.3'
services:

  # base config for all services in this compose
  base: &gex_base
    image: 'nginx'
    restart: always
    labels:
      - "com.gex.prefix=core"

  # api containers
  api:
    <<: *gex_base
    container_name: gexcore-api
    image: dockerhub.gex:5043/api:main
    tty: true
    networks:
      weave:
        ipv4_address: 51.0.${ENV_IP}.20
    #environment:
      #MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  mysql:
    <<: *gex_base
    container_name: gexcore-mysql
    image: 'mysql:5.7.15'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./containers/mysql/config:/etc/mysql/mysql.conf.d
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    <<: *gex_base
    container_name: gexcore-phpmyadmin
    image: 'corbinu/docker-phpmyadmin'
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PORT_3306_TCP_ADDR: mysql


  redis:
    <<: *gex_base
    container_name: gexcore-redis
    image: dockerhub.gex:5043/redis:main
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # TODO
  eth_bootnode:
    container_name: gexcore-eth-bootnode
    image: dockerhub.gex:5043/bootnode:main
    command: 'geth --datadir=~/.ethereum/devchain --nodekeyhex=80767334e357b60e41092e87288d35da9ea3f6f07afd2a38f15ac85a64f488ae --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"

    # --nodekeyhex 80767334e357b60e41092e87288d35da9ea3f6f07afd2a38f15ac85a64f488ae
    # enode://c8f362d19809d903a55bbef32052d4168ede760d086c92d1cb57f1cb557b29f5c8409684f527c861c43f1e9f2d510d9e4bbf92a6bc9542c0f12bf9c76888c55d

  netstats:
    image: dockerhub.gex:5043/netstats:main
    container_name: gexcore-netstats
    command: npm start --prefix /eth-netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
      - RPC_HOST=46.172.71.54
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"

  provisioner:
    hostname: provisioner
    container_name: gexcore-provisioner
    image: dockerhub.gex:5043/provisioner:main
    command: /sbin/my_init
    networks:
      weave:
        ipv4_address: 51.0.${ENV_IP}.55
    volumes:
      - /projects:/projects

  openvpn:
    hostname: openvpn
    container_name: gexcore-openvpn
    image: dockerhub.gex:5043/openvpn:main
    command: /etc/bootstrap.sh
    networks:
      weave:
        ipv4_address: 51.0.${ENV_IP}.8
    volumes:
      - /projects:/projects
      - /openvpn/data/consul_logs:/data/consul_logs
      - /openvpn/etc/supervisor/conf.d/:/etc/supervisor/conf.d
      - /openvpn/etc/consul/:/etc/consul/

  nginx_proxy:
    hostname: nginx_proxy
    restart: always
    container_name:  gexcore-nginx_proxy
    image: 'nginx'
    ports:
      - '80:80'
    volumes:
      - ./nginx_proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf

  # Application: -----------------------------------------------------------------
#  app:
#    <<: *gex_base
#    container_name: gexcore-app
#    image: dockerhub.gex:5043/app:main
#    build: ./containers/app
#    volumes:
#      - app_apps:/home/app/apps
#      - app_log:/var/log/nginx/
#
#    ports:
#      - "28089:80"
#      - "28022:22"
#
#    labels:
#      prerun: 'touch /tmp/id.test'
#      postrun: 'cat /tmp/id.test'
#    dns: 10.1.0.19
#    extra_hosts:
#     - "git.gex:46.172.71.53"


volumes:
  mysql_data:
  redis_data:
  app_apps:
  app_log:


networks:
  public:
    external:
      name: public
  weave:
    external:
      name: weave