version: '3.3'

services:
  vault:
    image: "vault"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./files/file:/vault/file
      - ./files/config/vault:/config
      - ./files/config/vault/policies:/policies
      - /mnt/vault/data
    entrypoint: vault server -config=/config/file-system.hcl
    restart: unless-stopped
    networks:
      weave:
        ipv4_address: 51.0.2.2

networks:
  weave:
    external:
      name: weave